# Generated by Django 3.0.6 on 2020-07-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipping',
            new_name='ShippingAddress',
        ),
    ]
